api = "0.7"

[buildpack]
  id = "maksimkurb/pip-preinstall"
  version = "0.0.1"

[metadata]
  [[metadata.configurations]]
    build = true
    default = ""
    description = "python libraries to preinstall"
    name = "BP_PREINSTALL_PYTHON_LIBS"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "*"
